"$schema" = 'https://starship.rs/config-schema.json'
format = """
$directory \
$character
"""

palette = "gruvbox_dark"
add_newline = false

[directory]
style = "color_blue"
format = "[$path]($style)"
truncation_length = 1
truncation_symbol = "~/"
home_symbol = "adam"

[character]
success_symbol = "[\\$](color_text)"
error_symbol   = "[\\$](color_red)"

[palettes.gruvbox_dark]
color_text = 'ebdbb2'
color_blue = '#83a598'
color_red = '#cc241d'
