"$schema" = 'https://starship.rs/config-schema.json'
format = """
$directory \
$username \
[~](color_text) \
$character
"""

palette = "gruvbox_dark"

[directory]
style = "italic bold color_blue"
format = "\\[[$path]($style)\\]"
truncation_length = 1
truncation_symbol = "~/"
home_symbol = "adam"

[username]
style_root = "bold color_green"
style_user = "bold color_green"
format = "[upon \\[[$user]($style)\\]](color_text)"
aliases = { "jayco" = "moses"}
show_always = true

[line_break]
disabled = false

[character]
success_symbol = "[\\$](color_orange)"
error_symbol   = "[\\$](color_red)"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_text = 'ebdbb2'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#83a598'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
